# Generated by Django 5.0.7 on 2024-09-07 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='stickers/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('Public Safety Incidents', 'Public Safety Incidents'), ('Public Health and Sanitation', 'Public Health and Sanitation'), ('Infrastructure Issues', 'Infrastructure Issues'), ('Environmental Concerns', 'Environmental Concerns'), ('Social Services and Welfare', 'Social Services and Welfare'), ('Community Engagement', 'Community Engagement'), ('Emergency Services', 'Emergency Services')], default='Public Safety Incidents', max_length=100)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Low', max_length=10)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='submitted', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], max_length=50)),
                ('update_description', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('category', models.CharField(choices=[('Public Safety Incidents', 'Public Safety Incidents'), ('Public Health and Sanitation', 'Public Health and Sanitation'), ('Infrastructure Issues', 'Infrastructure Issues'), ('Environmental Concerns', 'Environmental Concerns'), ('Social Services and Welfare', 'Social Services and Welfare'), ('Community Engagement', 'Community Engagement'), ('Emergency Services', 'Emergency Services')], default='Public Safety Incidents', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Low', max_length=10)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='reported', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='sticker',
            constraint=models.UniqueConstraint(fields=('report_id',), name='unique_sticker_report_id'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='sticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelines', to='sticker_app.sticker'),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.UniqueConstraint(fields=('report_id',), name='unique_issue_report_id'),
        ),
    ]
