# Generated by Django 5.0.7 on 2024-07-18 13:24

import sticker_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='image',
            field=models.ImageField(upload_to=sticker_app.models.sticker_image_path),
        ),
    ]
