# Generated by Django 5.0.7 on 2024-08-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticker_app', '0002_alter_sticker_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='category',
            field=models.CharField(choices=[('Public Safety Incidents', 'Public Safety Incidents'), ('Public Health and Sanitation', 'Public Health and Sanitation'), ('Infrastructure Issues', 'Infrastructure Issues'), ('Environmental Concerns', 'Environmental Concerns'), ('Social Services and Welfare', 'Social Services and Welfare'), ('Community Engagement', 'Community Engagement'), ('Emergency Services', 'Emergency Services')], default='Public Safety Incidents', max_length=100),
        ),
        migrations.AddField(
            model_name='sticker',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sticker',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sticker',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Low', max_length=10),
        ),
    ]
