# Generated by Django 5.0.7 on 2025-01-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticker_app', '0002_sticker_user_alter_issue_user_alter_sticker_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='location',
        ),
        migrations.RemoveField(
            model_name='sticker',
            name='location',
        ),
        migrations.AddField(
            model_name='issue',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='ward',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sticker',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sticker',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sticker',
            name='ward',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
