# Generated by Django 5.0.7 on 2025-01-22 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sticker_app', '0003_remove_issue_location_remove_sticker_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sticker',
            name='ward',
        ),
    ]
