# Generated by Django 5.0.7 on 2025-01-26 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sticker_app', '0004_remove_sticker_ward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='sticker',
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
        migrations.DeleteModel(
            name='Timeline',
        ),
    ]
