# Generated by Django 5.0.7 on 2025-02-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticker_app', '0007_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ward',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
