# Generated by Django 5.0.7 on 2025-02-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticker_app', '0008_userprofile_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ward',
            field=models.CharField(choices=[('Gintota', 'Gintota'), ('Dadalla', 'Dadalla'), ('Bope', 'Bope'), ('Kumbalwella', 'Kumbalwella'), ('Madawalamulla', 'Madawalamulla'), ('Deddugoda', 'Deddugoda'), ('Maitipe', 'Maitipe'), ('Dangedara', 'Dangedara'), ('Bataganvila', 'Bataganvila'), ('Sangamiththapura', 'Sangamiththapura'), ('Galwadugoda', 'Galwadugoda'), ('Kandewaththa', 'Kandewaththa'), ('Kaluwella', 'Kaluwella'), ('Galle Town', 'Galle Town'), ('Weliwaththa', 'Weliwaththa'), ('Thalapitiya', 'Thalapitiya'), ('Makuluwa', 'Makuluwa'), ('Milidduwa', 'Milidduwa'), ('Magalle', 'Magalle'), ('Katugoda', 'Katugoda')], default='Unknown', max_length=50),
        ),
    ]
