# Generated by Django 5.0.7 on 2025-02-04 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticker_app', '0009_userprofile_migration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward', models.CharField(blank=True, choices=[('Gintota', 'Gintota'), ('Dadalla', 'Dadalla'), ('Bope', 'Bope'), ('Kumbalwella', 'Kumbalwella'), ('Madawalamulla', 'Madawalamulla'), ('Deddugoda', 'Deddugoda'), ('Maitipe', 'Maitipe'), ('Dangedara', 'Dangedara'), ('Bataganvila', 'Bataganvila'), ('Sangamiththapura', 'Sangamiththapura'), ('Galwadugoda', 'Galwadugoda'), ('Kandewaththa', 'Kandewaththa'), ('Kaluwella', 'Kaluwella'), ('Galle Town', 'Galle Town'), ('Weliwaththa', 'Weliwaththa'), ('Thalapitiya', 'Thalapitiya'), ('Makuluwa', 'Makuluwa'), ('Milidduwa', 'Milidduwa'), ('Magalle', 'Magalle'), ('Katugoda', 'Katugoda')], max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
